/**
 * Dangerous Goods Database
 *
 * Comprehensive database of 90+ items for China-to-Africa shipping verification.
 * Covers electronics, cosmetics, food, machinery, medical, dangerous materials,
 * weapons, documents, agriculture, and textiles.
 */

import { DangerousGoodsItem, StatusConfig } from './types';

export const STATUS_CONFIGS: Record<string, StatusConfig> = {
  allowed: {
    status: 'allowed',
    label: 'Allowed',
    labelFr: 'Autorisé',
    color: 'emerald',
    bgColor: 'bg-emerald-500',
    icon: 'CheckCircle2',
    description: 'Can ship normally with standard packaging.',
    descriptionFr: 'Expédition normale avec emballage standard.',
  },
  restricted: {
    status: 'restricted',
    label: 'Restricted',
    labelFr: 'Restreint',
    color: 'amber',
    bgColor: 'bg-amber-500',
    icon: 'AlertTriangle',
    description: 'Needs special packaging, declaration, or handling.',
    descriptionFr: 'Nécessite un emballage spécial, déclaration ou manipulation particulière.',
  },
  prohibited: {
    status: 'prohibited',
    label: 'Prohibited',
    labelFr: 'Interdit',
    color: 'rose',
    bgColor: 'bg-rose-500',
    icon: 'Ban',
    description: 'Cannot ship under any circumstances.',
    descriptionFr: 'Expédition interdite en toutes circonstances.',
  },
  'permit-required': {
    status: 'permit-required',
    label: 'Permit Required',
    labelFr: 'Permis Requis',
    color: 'blue',
    bgColor: 'bg-blue-500',
    icon: 'FileCheck',
    description: 'Requires import license or special permit.',
    descriptionFr: 'Nécessite une licence d\'importation ou un permis spécial.',
  },
};

export const CATEGORIES = [
  { id: 'all', name: 'All Categories', nameFr: 'Toutes les Catégories' },
  { id: 'electronics', name: 'Electronics', nameFr: 'Électronique' },
  { id: 'cosmetics', name: 'Cosmetics', nameFr: 'Cosmétiques' },
  { id: 'food', name: 'Food & Beverages', nameFr: 'Alimentation & Boissons' },
  { id: 'textiles', name: 'Textiles & Clothing', nameFr: 'Textiles & Vêtements' },
  { id: 'machinery', name: 'Machinery & Tools', nameFr: 'Machines & Outils' },
  { id: 'medical', name: 'Medical & Pharmaceuticals', nameFr: 'Médical & Pharmaceutique' },
  { id: 'dangerous', name: 'Dangerous Materials', nameFr: 'Matériaux Dangereux' },
  { id: 'weapons', name: 'Weapons & Security', nameFr: 'Armes & Sécurité' },
  { id: 'documents', name: 'Documents & Money', nameFr: 'Documents & Argent' },
  { id: 'agriculture', name: 'Agriculture', nameFr: 'Agriculture' },
] as const;

export const DANGEROUS_GOODS_ITEMS: DangerousGoodsItem[] = [
  // ELECTRONICS (10 items)
  {
    id: 'smartphone',
    name: 'Smartphone / Mobile Phone',
    nameFr: 'Smartphone / Téléphone Mobile',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Contains lithium battery. Must be declared. Phones should be packed with battery installed and device powered off. Maximum 2-4 units per shipment for personal use.',
    descriptionFr: 'Contient une batterie lithium. Doit être déclaré. Les téléphones doivent être emballés avec la batterie installée et l\'appareil éteint. Maximum 2-4 unités par envoi pour usage personnel.',
    icon: 'Smartphone',
    notes: 'Remove SIM cards. Declare battery capacity (mAh) on invoice.',
    notesFr: 'Retirer les cartes SIM. Déclarer la capacité de la batterie (mAh) sur la facture.',
  },
  {
    id: 'laptop',
    name: 'Laptop / Notebook Computer',
    nameFr: 'Ordinateur Portable',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Lithium battery device. Must be properly packaged with original foam or bubble wrap. Battery should not exceed 100Wh. Declare on shipping invoice.',
    descriptionFr: 'Appareil à batterie lithium. Doit être correctement emballé avec mousse d\'origine ou film à bulles. La batterie ne doit pas dépasser 100Wh. Déclarer sur la facture d\'expédition.',
    icon: 'Laptop',
    notes: 'Maximum 2 laptops per personal shipment. Keep original packaging if possible.',
    notesFr: 'Maximum 2 ordinateurs portables par envoi personnel. Conserver l\'emballage d\'origine si possible.',
  },
  {
    id: 'power-bank',
    name: 'Power Bank / Portable Charger',
    nameFr: 'Batterie Externe / Chargeur Portable',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'High-risk lithium battery item. Capacity must be clearly printed on the unit. Maximum 20,000mAh per unit for air freight. Requires MSDS documentation for large capacities.',
    descriptionFr: 'Article à batterie lithium à haut risque. La capacité doit être clairement imprimée sur l\'unité. Maximum 20 000mAh par unité en fret aérien. Nécessite une documentation MSDS pour les grandes capacités.',
    icon: 'BatteryCharging',
    notes: 'Must have capacity label (mAh and Wh). No unbranded power banks accepted.',
    notesFr: 'Doit avoir une étiquette de capacité (mAh et Wh). Aucune batterie externe sans marque n\'est acceptée.',
  },
  {
    id: 'bluetooth-speaker',
    name: 'Bluetooth Speaker',
    nameFr: 'Enceinte Bluetooth',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'allowed',
    description: 'Generally allowed if battery is internal and under 100Wh. Standard consumer electronics packaging is sufficient.',
    descriptionFr: 'Généralement autorisé si la batterie est interne et inférieure à 100Wh. L\'emballage standard des produits électroniques est suffisant.',
    icon: 'Volume2',
  },
  {
    id: 'tablet',
    name: 'Tablet / iPad',
    nameFr: 'Tablette / iPad',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Lithium battery device. Same rules as smartphones and laptops. Must be powered off and properly cushioned.',
    descriptionFr: 'Appareil à batterie lithium. Mêmes règles que les smartphones et ordinateurs portables. Doit être éteint et correctement amorti.',
    icon: 'Tablet',
  },
  {
    id: 'camera',
    name: 'Digital Camera / DSLR',
    nameFr: 'Appareil Photo Numérique / DSLR',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Battery must remain inside device. Remove memory cards for customs inspection if requested. Declare lithium battery.',
    descriptionFr: 'La batterie doit rester à l\'intérieur de l\'appareil. Retirer les cartes mémoire pour l\'inspection douanière si demandé. Déclarer la batterie lithium.',
    icon: 'Camera',
  },
  {
    id: 'drone',
    name: 'Drone / UAV',
    nameFr: 'Drone / UAV',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Multiple lithium batteries. Must declare total battery capacity. Some African countries require drone import permits. Remove propellers for shipping.',
    descriptionFr: 'Plusieurs batteries lithium. Doit déclarer la capacité totale des batteries. Certains pays africains nécessitent un permis d\'importation de drones. Retirer les hélices pour l\'expédition.',
    icon: 'Plane',
    notes: 'Check destination country drone regulations. Cameroon requires Ministry of Defense authorization.',
    notesFr: 'Vérifier la réglementation des drones du pays de destination. Le Cameroun nécessite une autorisation du Ministère de la Défense.',
  },
  {
    id: 'electric-scooter',
    name: 'Electric Scooter / E-Bike',
    nameFr: 'Trottinette Électrique / Vélo Électrique',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'restricted',
    description: 'Large lithium battery. Often classified as dangerous goods. Requires special freight handling. Battery may need to be shipped separately via sea freight.',
    descriptionFr: 'Grande batterie lithium. Souvent classée comme marchandise dangereuse. Nécessite une manipulation fret spéciale. La batterie peut devoir être expédiée séparément par fret maritime.',
    icon: 'Bike',
    notes: 'Sea freight strongly recommended. Battery UN38.3 test report required.',
    notesFr: 'Fret maritime fortement recommandé. Rapport de test UN38.3 de la batterie requis.',
  },
  {
    id: 'smart-watch',
    name: 'Smart Watch / Fitness Tracker',
    nameFr: 'Montre Connectée / Bracelet Fitness',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'allowed',
    description: 'Small lithium battery, generally allowed in reasonable quantities for personal use. Standard packaging.',
    descriptionFr: 'Petite batterie lithium, généralement autorisée en quantités raisonnables pour usage personnel. Emballage standard.',
    icon: 'Watch',
  },
  {
    id: 'hair-dryer',
    name: 'Hair Dryer / Hair Straightener',
    nameFr: 'Sèche-Cheveux / Lisseur',
    category: 'electronics',
    categoryFr: 'Électronique',
    status: 'allowed',
    description: 'Standard household appliance. No special restrictions. Proper electrical plug adapter may be needed for local use.',
    descriptionFr: 'Appareil électroménager standard. Aucune restriction spéciale. Un adaptateur de prise électrique peut être nécessaire pour l\'usage local.',
    icon: 'Wind',
  },

  // COSMETICS (10 items)
  {
    id: 'perfume',
    name: 'Perfume / Eau de Toilette',
    nameFr: 'Parfum / Eau de Toilette',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'restricted',
    description: 'Flammable liquid (alcohol content > 60%). Limited to 500ml per shipment for air freight. Must be in original sealed packaging with proper cushioning.',
    descriptionFr: 'Liquide inflammable (teneur en alcool > 60%). Limité à 500ml par envoi en fret aérien. Doit être dans l\'emballage scellé d\'origine avec amortissement approprié.',
    icon: 'Droplets',
    notes: 'Air freight: max 500ml. Sea freight: no strict limit but declare.',
    notesFr: 'Fret aérien: max 500ml. Fret maritime: pas de limite stricte mais déclarer.',
  },
  {
    id: 'nail-polish',
    name: 'Nail Polish / Nail Polish Remover',
    nameFr: 'Vernis à Ongles / Dissolvant',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'restricted',
    description: 'Flammable liquid and vapor. Limited quantities for air freight. Must be packed upright with leak-proof seals. Acetone-based removers are higher risk.',
    descriptionFr: 'Liquide et vapeur inflammables. Quantités limitées en fret aérien. Doit être emballé à la verticale avec des joints étanches. Les dissolvants à base d\'acétone sont à plus haut risque.',
    icon: 'Paintbrush',
    notes: 'Max 1L total per shipment by air. Wrap each bottle individually.',
    notesFr: 'Max 1L total par envoi par avion. Envelopper chaque bouteille individuellement.',
  },
  {
    id: 'hair-spray',
    name: 'Hair Spray / Aerosol',
    nameFr: 'Laque / Aérosol',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'restricted',
    description: 'Pressurized flammable aerosol. Strictly limited for air freight. Many airlines refuse aerosols entirely. Sea freight recommended for bulk quantities.',
    descriptionFr: 'Aérosol inflammable sous pression. Strictement limité en fret aérien. De nombreuses compagnies aériennes refusent totalement les aérosols. Fret maritime recommandé pour les grandes quantités.',
    icon: 'SprayCan',
    notes: 'Check with airline before booking. Consider sea freight for orders > 5 cans.',
    notesFr: 'Vérifier auprès de la compagnie aérienne avant la réservation. Envisager le fret maritime pour les commandes > 5 bombes.',
  },
  {
    id: 'face-cream',
    name: 'Face Cream / Moisturizer',
    nameFr: 'Crème Visage / Hydratant',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'allowed',
    description: 'Standard cosmetic cream. No restrictions. Ensure packaging is sealed to prevent leakage during transit.',
    descriptionFr: 'Crème cosmétique standard. Aucune restriction. S\'assurer que l\'emballage est scellé pour éviter les fuites pendant le transport.',
    icon: 'Sparkles',
  },
  {
    id: 'sunscreen',
    name: 'Sunscreen / Sunblock',
    nameFr: 'Crème Solaire / Écran Solaire',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'allowed',
    description: 'Allowed without restriction. Popular item for African market. Ensure bottles are well-sealed and packed upright.',
    descriptionFr: 'Autorisé sans restriction. Article populaire pour le marché africain. S\'assurer que les bouteilles sont bien scellées et emballées à la verticale.',
    icon: 'Sun',
  },
  {
    id: 'makeup',
    name: 'Makeup / Cosmetics Kit',
    nameFr: 'Maquillage / Kit Cosmétique',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'allowed',
    description: 'General makeup products (powder, lipstick, eyeshadow) are allowed. Nail polish and spray items within the kit must follow their own rules.',
    descriptionFr: 'Les produits de maquillage généraux (poudre, rouge à lèvres, fard à paupières) sont autorisés. Le vernis à ongles et les articles en spray dans le kit doivent suivre leurs propres règles.',
    icon: 'Palette',
  },
  {
    id: 'essential-oil',
    name: 'Essential Oils',
    nameFr: 'Huiles Essentielles',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'restricted',
    description: 'Flammable liquid. Quantity limits apply for air freight. Must have proper dropper or sealed caps. Glass bottles need extra cushioning.',
    descriptionFr: 'Liquide inflammable. Des limites de quantité s\'appliquent pour le fret aérien. Doit avoir un compte-gouttes ou des bouchons scellés appropriés. Les bouteilles en verre nécessitent un amortissement supplémentaire.',
    icon: 'Droplet',
    notes: 'Max 1L total by air. Wrap glass bottles in bubble wrap individually.',
    notesFr: 'Max 1L total par avion. Envelopper les bouteilles en verre dans du film à bulles individuellement.',
  },
  {
    id: 'hair-dye',
    name: 'Hair Dye / Hair Color',
    nameFr: 'Coloration Cheveux / Teinture',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'restricted',
    description: 'Contains ammonia and peroxide. Some formulations are classified as dangerous goods. Check SDS (Safety Data Sheet) from supplier.',
    descriptionFr: 'Contient de l\'ammoniac et du peroxyde. Certaines formulations sont classées comme marchandises dangereuses. Vérifier la FDS (Fiche de Données de Sécurité) du fournisseur.',
    icon: 'PaintBucket',
    notes: 'Professional salon quantities may require sea freight.',
    notesFr: 'Les quantités pour salon professionnel peuvent nécessiter le fret maritime.',
  },
  {
    id: 'shampoo',
    name: 'Shampoo / Conditioner',
    nameFr: 'Shampooing / Après-Shampooing',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'allowed',
    description: 'Standard liquid cosmetic. No restrictions. Ensure caps are taped and bottles upright in box. Popular wholesale item.',
    descriptionFr: 'Cosmétique liquide standard. Aucune restriction. S\'assurer que les bouchons sont scotchés et les bouteilles à la verticale dans la boîte. Article populaire en gros.',
    icon: 'ShowerHead',
  },
  {
    id: 'deodorant-stick',
    name: 'Deodorant (Stick / Roll-on)',
    nameFr: 'Déodorant (Stick / Bille)',
    category: 'cosmetics',
    categoryFr: 'Cosmétiques',
    status: 'allowed',
    description: 'Non-aerosol deodorants are generally allowed. Aerosol/spray deodorants follow aerosol rules.',
    descriptionFr: 'Les déodorants non aérosol sont généralement autorisés. Les déodorants aérosol/spray suivent les règles des aérosols.',
    icon: 'CircleDot',
  },

  // FOOD & BEVERAGES (10 items)
  {
    id: 'canned-food',
    name: 'Canned Food / Preserves',
    nameFr: 'Conserve / Produit en Boîte',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Commercially canned foods are allowed. Ensure cans are not damaged or rusted. Best before date should be at least 6 months from shipping date.',
    descriptionFr: 'Les aliments en conserve commerciaux sont autorisés. S\'assurer que les boîtes ne sont pas endommagées ou rouillées. La date de péremption doit être d\'au moins 6 mois à partir de la date d\'expédition.',
    icon: 'Container',
    notes: 'Check destination country food import rules. Some countries ban pork products.',
    notesFr: 'Vérifier les règles d\'importation alimentaire du pays de destination. Certains pays interdisent les produits porcins.',
  },
  {
    id: 'spices',
    name: 'Spices / Seasonings',
    nameFr: 'Épices / Assaisonnements',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Dried spices in sealed packaging are allowed. Must be commercially packaged with ingredient list and origin label. No loose bulk spices.',
    descriptionFr: 'Les épices séchées dans un emballage scellé sont autorisées. Doivent être emballées commercialement avec la liste des ingrédients et l\'étiquette d\'origine. Pas d\'épices en vrac.',
    icon: 'Flame',
  },
  {
    id: 'alcohol',
    name: 'Alcoholic Beverages',
    nameFr: 'Boissons Alcoolisées',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'permit-required',
    description: 'Requires alcohol import license in most African countries. High duties apply (often 50-100% of value). Cameroon requires special excise permit. Age restrictions apply.',
    descriptionFr: 'Nécessite une licence d\'importation d\'alcool dans la plupart des pays africains. Des droits élevés s\'appliquent (souvent 50-100% de la valeur). Le Cameroun nécessite un permis d\'accise spécial. Des restrictions d\'âge s\'appliquent.',
    icon: 'Wine',
    notes: 'Contact us before ordering. We can assist with permit applications.',
    notesFr: 'Contactez-nous avant de commander. Nous pouvons aider aux demandes de permis.',
  },
  {
    id: 'cooking-oil',
    name: 'Cooking Oil / Vegetable Oil',
    nameFr: 'Huile de Cuisson / Huile Végétale',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Allowed in sealed commercial packaging. Large quantities may require food import registration. Use strong outer packaging to prevent leakage.',
    descriptionFr: 'Autorisé dans un emballage commercial scellé. Les grandes quantités peuvent nécessiter un enregistrement d\'importation alimentaire. Utiliser un emballage extérieur robuste pour éviter les fuites.',
    icon: 'Droplet',
  },
  {
    id: 'chocolate',
    name: 'Chocolate / Confectionery',
    nameFr: 'Chocolat / Confiserie',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Allowed. May melt in hot climates during sea freight. Consider climate-controlled shipping or air freight for chocolate in warm months.',
    descriptionFr: 'Autorisé. Peut fondre dans les climats chauds pendant le fret maritime. Envisager un transport climatisé ou le fret aérien pour le chocolat en saison chaude.',
    icon: 'Candy',
    notes: 'Air freight recommended for chocolate April-October.',
    notesFr: 'Fret aérien recommandé pour le chocolat d\'avril à octobre.',
  },
  {
    id: 'instant-noodles',
    name: 'Instant Noodles / Instant Food',
    nameFr: 'Nouilles Instantanées / Aliment Instantané',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Very popular import item. Allowed without restriction. Ensure packaging is intact. Check for pork content if shipping to Muslim-majority countries.',
    descriptionFr: 'Article d\'importation très populaire. Autorisé sans restriction. S\'assurer que l\'emballage est intact. Vérifier la teneur en porc si expédition vers des pays à majorité musulmane.',
    icon: 'Soup',
  },
  {
    id: 'baby-formula',
    name: 'Baby Formula / Infant Milk',
    nameFr: 'Lait Infantile / Formule Bébé',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'permit-required',
    description: 'Requires health ministry import permit and sanitary certificate in most African countries. Strict expiry date requirements. Temperature-sensitive.',
    descriptionFr: 'Nécessite un permis d\'importation du ministère de la santé et un certificat sanitaire dans la plupart des pays d\'Afrique. Exigences strictes de date de péremption. Sensible à la température.',
    icon: 'Baby',
    notes: 'Pharmaceutical-grade cold chain may be needed. Contact us for guidance.',
    notesFr: 'Une chaîne du froid de qualité pharmaceutique peut être nécessaire. Contactez-nous pour des conseils.',
  },
  {
    id: 'tea-coffee',
    name: 'Tea / Coffee / Beverages',
    nameFr: 'Thé / Café / Boissons',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'allowed',
    description: 'Packaged tea and coffee are allowed. Loose tea needs commercial vacuum sealing. Energy drinks with high caffeine may have restrictions in some countries.',
    descriptionFr: 'Le thé et le café emballés sont autorisés. Le thé en vrac nécessite un scellage sous vide commercial. Les boissons énergisantes avec forte teneur en caféine peuvent avoir des restrictions dans certains pays.',
    icon: 'Coffee',
  },
  {
    id: 'frozen-food',
    name: 'Frozen / Fresh Food',
    nameFr: 'Aliment Surgelé / Frais',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'prohibited',
    description: 'Fresh meat, fish, dairy, and frozen foods are prohibited for standard freight. They require refrigerated containers (reefer) and sanitary certificates which we do not handle.',
    descriptionFr: 'La viande fraîche, le poisson, les produits laitiers et les aliments surgelés sont interdits pour le fret standard. Ils nécessitent des conteneurs réfrigérés (reefer) et des certificats sanitaires que nous ne gérons pas.',
    icon: 'Snowflake',
    notes: 'We do not offer cold chain logistics. Contact a specialized reefer forwarder.',
    notesFr: 'Nous n\'offrons pas de logistique de chaîne du froid. Contactez un transitaire spécialisé en reefer.',
  },
  {
    id: 'honey',
    name: 'Honey / Bee Products',
    nameFr: 'Miel / Produits de la Ruche',
    category: 'food',
    categoryFr: 'Alimentation & Boissons',
    status: 'permit-required',
    description: 'Requires veterinary/phytosanitary certificate in many countries. Must be pure honey (no adulteration). Origin certificate required. Some countries restrict honey imports to protect local beekeepers.',
    descriptionFr: 'Nécessite un certificat vétérinaire/phytosanitaire dans de nombreux pays. Doit être du miel pur (sans adultération). Certificat d\'origine requis. Certains pays restreignent les importations de miel pour protéger les apiculteurs locaux.',
    icon: 'Hexagon',
  },

  // TEXTILES & CLOTHING (8 items)
  {
    id: 'clothing',
    name: 'General Clothing / Apparel',
    nameFr: 'Vêtements Généraux / Habits',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Fully allowed. One of the most common import categories from China to Africa. No special restrictions. Ensure proper labeling for retail sale.',
    descriptionFr: 'Totalement autorisé. Une des catégories d\'importation les plus courantes de Chine vers l\'Afrique. Aucune restriction spéciale. S\'assurer d\'un étiquetage approprié pour la vente au détail.',
    icon: 'Shirt',
  },
  {
    id: 'shoes',
    name: 'Shoes / Footwear',
    nameFr: 'Chaussures / Souliers',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Leather shoes may need origin certificate if claiming genuine leather. Counterfeit branded shoes are prohibited.',
    descriptionFr: 'Autorisé. Les chaussures en cuir peuvent nécessiter un certificat d\'origine si cuir véritable revendiqué. Les chaussures de contrefaçon de marque sont interdites.',
    icon: 'Footprints',
  },
  {
    id: 'fabric',
    name: 'Fabric / Textile Rolls',
    nameFr: 'Tissu / Rouleaux Textiles',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Very popular for African market (wax print, chiffon, etc.). No restrictions. Bulk sea freight recommended for large quantities.',
    descriptionFr: 'Autorisé. Très populaire pour le marché africain (wax, chiffon, etc.). Aucune restriction. Fret maritime en vrac recommandé pour les grandes quantités.',
    icon: 'ScrollText',
  },
  {
    id: 'wigs',
    name: 'Wigs / Hair Extensions',
    nameFr: 'Perruques / Extensions de Cheveux',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Human hair wigs may need sanitary certificate depending on destination. Synthetic wigs have no restrictions. Very popular import item.',
    descriptionFr: 'Autorisé. Les perruques en cheveux humains peuvent nécessiter un certificat sanitaire selon la destination. Les perruques synthétiques n\'ont aucune restriction. Article d\'importation très populaire.',
    icon: 'Scissors',
  },
  {
    id: 'bags',
    name: 'Bags / Luggage / Purses',
    nameFr: 'Sacs / Bagages / Sacs à Main',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Counterfeit designer bags are strictly prohibited and may be seized by customs. Ensure authentic or generic branding.',
    descriptionFr: 'Autorisé. Les sacs de contrefaçon de marque sont strictement interdits et peuvent être saisis par les douanes. S\'assurer d\'une marque authentique ou générique.',
    icon: 'ShoppingBag',
  },
  {
    id: 'jewelry',
    name: 'Costume Jewelry / Accessories',
    nameFr: 'Bijoux Fantaisie / Accessoires',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Gold, silver, or precious stone jewelry may require special customs declaration and duties. Magnetic clasps on jewelry are fine.',
    descriptionFr: 'Autorisé. Les bijoux en or, argent ou pierres précieuses peuvent nécessiter une déclaration douanière spéciale et des droits. Les fermoirs magnétiques sur les bijoux sont acceptés.',
    icon: 'Gem',
  },
  {
    id: 'belts',
    name: 'Belts / Leather Accessories',
    nameFr: 'Ceintures / Accessoires en Cuir',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed. Genuine leather products may need CITES documentation if from endangered species (exotic skins). Standard cow leather is fine.',
    descriptionFr: 'Autorisé. Les produits en cuir véritable peuvent nécessiter une documentation CITES si issus d\'espèces en danger (peaux exotiques). Le cuir de vache standard est accepté.',
    icon: 'Link',
  },
  {
    id: 'hats',
    name: 'Hats / Caps / Headwear',
    nameFr: 'Chapeaux / Casquettes / Couvre-Chefs',
    category: 'textiles',
    categoryFr: 'Textiles & Vêtements',
    status: 'allowed',
    description: 'Allowed without restriction. Popular wholesale item. No special packaging needed.',
    descriptionFr: 'Autorisé sans restriction. Article populaire en gros. Aucun emballage spécial nécessaire.',
    icon: 'Cone',
  },

  // MACHINERY & TOOLS (9 items)
  {
    id: 'generator',
    name: 'Generator / Power Generator',
    nameFr: 'Groupe Électrogène / Générateur',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Heavy machinery ships best by sea (FCL). Must be drained of fuel before shipping. Oil and fuel are prohibited inside the unit.',
    descriptionFr: 'Autorisé. Les machines lourdes sont mieux expédiées par mer (FCL). Doit être vidé de carburant avant l\'expédition. L\'huile et le carburant sont interdits à l\'intérieur de l\'unité.',
    icon: 'Zap',
    notes: 'Drain all fluids. Battery must be disconnected and terminals protected.',
    notesFr: 'Vider tous les liquides. La batterie doit être débranchée et les bornes protégées.',
  },
  {
    id: 'power-tools',
    name: 'Power Tools (Drill, Saw, Grinder)',
    nameFr: 'Outils Électriques (Perceuse, Scie, Meuleuse)',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'restricted',
    description: 'Contains lithium or NiCd batteries. Battery-powered tools must have battery declared. Corded tools have fewer restrictions. Ensure proper protective packaging for sharp edges.',
    descriptionFr: 'Contient des batteries lithium ou NiCd. Les outils à batterie doivent avoir la batterie déclarée. Les outils filaires ont moins de restrictions. S\'assurer d\'un emballage de protection approprié pour les arêtes vives.',
    icon: 'Wrench',
  },
  {
    id: 'welding-machine',
    name: 'Welding Machine / Equipment',
    nameFr: 'Poste à Souder / Équipement de Soudure',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Heavy item best suited for sea freight. Must be properly crated. Remove gas cylinders (prohibited) before shipping.',
    descriptionFr: 'Autorisé. Article lourd mieux adapté au fret maritime. Doit être correctement caissé. Retirer les bouteilles de gaz (interdites) avant l\'expédition.',
    icon: 'Flame',
    notes: 'Gas cylinders must be shipped separately via specialized hazardous cargo.',
    notesFr: 'Les bouteilles de gaz doivent être expédiées séparément par cargo spécialisé pour marchandises dangereuses.',
  },
  {
    id: 'car-parts',
    name: 'Car / Motorcycle Parts',
    nameFr: 'Pièces Auto / Moto',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Very popular import. Brake pads, filters, spark plugs, etc. are fine. Airbags are prohibited (explosive charge). Used tires may be banned in some countries.',
    descriptionFr: 'Autorisé. Importation très populaire. Plaquettes de frein, filtres, bougies, etc. sont acceptés. Les airbags sont interdits (charge explosive). Les pneus d\'occasion peuvent être interdits dans certains pays.',
    icon: 'Cog',
    notes: 'Airbags = PROHIBITED. Check used tire import bans for your country.',
    notesFr: 'Airbags = INTERDIT. Vérifier les interdictions d\'importation de pneus d\'occasion pour votre pays.',
  },
  {
    id: 'agriculture-machine',
    name: 'Agricultural Machinery',
    nameFr: 'Machines Agricoles',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Tractors, threshers, mills, etc. Ship by sea FCL. Must be clean (no soil residue) to prevent biosecurity issues.',
    descriptionFr: 'Autorisé. Tracteurs, batteuses, moulins, etc. Expédition par FCL maritime. Doit être propre (pas de résidus de sol) pour éviter les problèmes de biosécurité.',
    icon: 'Tractor',
    notes: 'Clean all soil and plant matter before crating. Some countries inspect for cleanliness.',
    notesFr: 'Nettoyer tout le sol et la matière végétale avant le caissage. Certains pays inspectent la propreté.',
  },
  {
    id: 'compressor',
    name: 'Air Compressor',
    nameFr: 'Compresseur d\'Air',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Drain all oil and fuel. Heavy item - sea freight recommended. Secure loose parts to prevent damage.',
    descriptionFr: 'Autorisé. Vider toute l\'huile et le carburant. Article lourd - fret maritime recommandé. Sécuriser les pièces mobiles pour éviter les dommages.',
    icon: 'Wind',
  },
  {
    id: 'bicycle',
    name: 'Bicycle / Motorcycle',
    nameFr: 'Vélo / Moto',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Allowed. Must be partially disassembled for efficient packing. Remove battery if electric. Lithium batteries follow electronics rules.',
    descriptionFr: 'Autorisé. Doit être partiellement démonté pour un emballage efficace. Retirer la batterie si électrique. Les batteries lithium suivent les règles de l\'électronique.',
    icon: 'Bike',
  },
  {
    id: 'refrigerator',
    name: 'Refrigerator / Freezer / AC',
    nameFr: 'Réfrigérateur / Congélateur / Climatiseur',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'restricted',
    description: 'Contains refrigerant gas. Must be properly declared. Some refrigerants are ozone-depleting and restricted under Montreal Protocol. Compressor units may contain oil.',
    descriptionFr: 'Contient du gaz réfrigérant. Doit être correctement déclaré. Certains réfrigérants appauvrissent la couche d\'ozone et sont restreints par le Protocole de Montréal. Les unités compresseur peuvent contenir de l\'huile.',
    icon: 'ThermometerSnowflake',
    notes: 'Ensure refrigerant is R410A or modern type. Older CFC/HCFC refrigerants may be prohibited.',
    notesFr: 'S\'assurer que le réfrigérant est de type R410A ou moderne. Les réfrigérants CFC/HCFC anciens peuvent être interdits.',
  },
  {
    id: ' solar-panel',
    name: 'Solar Panel / Inverter / Battery',
    nameFr: 'Panneau Solaire / Onduleur / Batterie',
    category: 'machinery',
    categoryFr: 'Machines & Outils',
    status: 'allowed',
    description: 'Solar panels and inverters are allowed. Battery component follows lithium battery rules if applicable. Glass panels need protective crating.',
    descriptionFr: 'Les panneaux solaires et onduleurs sont autorisés. La composante batterie suit les règles des batteries lithium si applicable. Les panneaux en verre nécessitent un caissage de protection.',
    icon: 'Sun',
  },

  // MEDICAL & PHARMACEUTICALS (9 items)
  {
    id: 'prescription-medicine',
    name: 'Prescription Medicine / Drugs',
    nameFr: 'Médicament sur Ordonnance / Médicaments',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'permit-required',
    description: 'Requires pharmaceutical import license and Ministry of Health registration in destination country. Original prescription and commercial invoice required. Temperature-controlled shipping for some medicines.',
    descriptionFr: 'Nécessite une licence d\'importation pharmaceutique et un enregistrement au Ministère de la Santé du pays de destination. Ordonnance originale et facture commerciale requises. Transport contrôlé en température pour certains médicaments.',
    icon: 'Pill',
    notes: 'We do NOT ship narcotics, opioids, or controlled substances under any circumstances.',
    notesFr: 'Nous n\'expédions PAS de stupéfiants, opioïdes ou substances contrôlées en aucune circonstance.',
  },
  {
    id: 'syringes',
    name: 'Syringes / Needles / Medical Tools',
    nameFr: 'Seringues / Aiguilles / Outils Médicaux',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'permit-required',
    description: 'Requires medical device import permit. Must be sterile and in original sealed packaging. Sharps must have safety caps. HIV test kits have additional restrictions.',
    descriptionFr: 'Nécessite un permis d\'importation de dispositifs médicaux. Doit être stérile et dans l\'emballage scellé d\'origine. Les objets tranchants doivent avoir des capuchons de sécurité. Les kits de test VIH ont des restrictions supplémentaires.',
    icon: 'Syringe',
  },
  {
    id: 'face-mask',
    name: 'Face Masks / PPE / Gloves',
    nameFr: 'Masques / EPI / Gants',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Allowed. No longer restricted post-COVID. Must meet local standards (e.g., CE mark, FDA registration if claiming medical grade). Standard disposable masks have no restrictions.',
    descriptionFr: 'Autorisé. Plus restreint post-COVID. Doit répondre aux normes locales (marque CE, enregistrement FDA si grade médical revendiqué). Les masques jetables standard n\'ont aucune restriction.',
    icon: 'Shield',
  },
  {
    id: 'vitamins',
    name: 'Vitamins / Supplements',
    nameFr: 'Vitamines / Compléments Alimentaires',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Dietary supplements are generally allowed in reasonable personal quantities. Bulk commercial imports may need food/pharmaceutical registration. Must have ingredient labels.',
    descriptionFr: 'Les compléments alimentaires sont généralement autorisés en quantités personnelles raisonnables. Les importations commerciales en vrac peuvent nécessiter un enregistrement alimentaire/pharmaceutique. Doivent avoir des étiquettes d\'ingrédients.',
    icon: 'Heart',
  },
  {
    id: 'thermometer',
    name: 'Thermometer / Blood Pressure Monitor',
    nameFr: 'Thermomètre / Tensiomètre',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Standard medical devices allowed. Mercury thermometers are prohibited (toxic). Digital devices with lithium batteries follow battery rules.',
    descriptionFr: 'Dispositifs médicaux standard autorisés. Les thermomètres à mercure sont interdits (toxiques). Les appareils numériques avec batteries lithium suivent les règles des batteries.',
    icon: 'Activity',
  },
  {
    id: 'disinfectant',
    name: 'Medical Disinfectant / Alcohol Swabs',
    nameFr: 'Désinfectant Médical / Tampons Alcoolisés',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'restricted',
    description: 'High alcohol content makes these flammable. Alcohol swabs are generally fine in small quantities. Bulk liquid disinfectant (>1L) follows flammable liquid rules.',
    descriptionFr: 'La forte teneur en alcool les rend inflammables. Les tampons alcoolisés sont généralement acceptés en petites quantités. Le désinfectant liquide en vrac (>1L) suit les règles des liquides inflammables.',
    icon: 'Droplets',
  },
  {
    id: 'dental-equipment',
    name: 'Dental Equipment / Tools',
    nameFr: 'Équipement Dentaire / Outils',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Allowed. Must be properly sterilized and packaged. X-ray equipment may require radiation safety permit. Sharp instruments need safety packaging.',
    descriptionFr: 'Autorisé. Doit être correctement stérilisé et emballé. L\'équipement à rayons X peut nécessiter un permis de sécurité radiologique. Les instruments tranchants nécessitent un emballage de sécurité.',
    icon: 'Smile',
  },
  {
    id: 'contact-lenses',
    name: 'Contact Lenses / Lens Solution',
    nameFr: 'Lentilles de Contact / Solution',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Allowed. Must be in original sealed packaging with expiry dates visible. Solution bottles should be taped and cushioned. Prescription lenses should include copy of prescription.',
    descriptionFr: 'Autorisé. Doit être dans l\'emballage scellé d\'origine avec les dates de péremption visibles. Les bouteilles de solution doivent être scotchées et amorties. Les lentilles sur ordonnance doivent inclure une copie de l\'ordonnance.',
    icon: 'Eye',
  },
  {
    id: 'first-aid',
    name: 'First Aid Kit / Bandages',
    nameFr: 'Trousse de Premiers Secours / Bandages',
    category: 'medical',
    categoryFr: 'Médical & Pharmaceutique',
    status: 'allowed',
    description: 'Allowed. Ensure any included medications (painkillers, antiseptics) are clearly labeled. Kits for personal use have no restrictions.',
    descriptionFr: 'Autorisé. S\'assurer que tous les médicaments inclus (antalgiques, antiseptiques) sont clairement étiquetés. Les trousses pour usage personnel n\'ont aucune restriction.',
    icon: 'Cross',
  },

  // DANGEROUS MATERIALS (10 items)
  {
    id: 'paint',
    name: 'Paint / Varnish / Lacquer',
    nameFr: 'Peinture / Vernis / Laque',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'restricted',
    description: 'Flammable liquid. Oil-based paints are more restricted than water-based. Limited quantities for air freight. Must be in original sealed cans with proper cushioning.',
    descriptionFr: 'Liquide inflammable. Les peintures à l\'huile sont plus restreintes que les peintures à l\'eau. Quantités limitées pour le fret aérien. Doit être dans des boîtes scellées d\'origine avec amortissement approprié.',
    icon: 'PaintBucket',
    notes: 'Water-based (latex) paint is less restricted. Max 5L by air per shipment.',
    notesFr: 'La peinture à l\'eau (latex) est moins restreinte. Max 5L par avion par envoi.',
  },
  {
    id: 'adhesive',
    name: 'Super Glue / Industrial Adhesive',
    nameFr: 'Super Glue / Adhésif Industriel',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'restricted',
    description: 'Cyanoacrylate and solvent-based adhesives are flammable. Limited quantities for air freight. Must have safety caps and be upright in box.',
    descriptionFr: 'Les adhésifs au cyanoacrylate et à base de solvant sont inflammables. Quantités limitées pour le fret aérien. Doit avoir des bouchons de sécurité et être à la verticale dans la boîte.',
    icon: 'Droplet',
    notes: 'Small consumer tubes (<20g) are usually fine. Bulk industrial drums require sea freight.',
    notesFr: 'Les petits tubes de consommation (<20g) sont généralement acceptés. Les fûts industriels en vrac nécessitent le fret maritime.',
  },
  {
    id: 'gas-cylinder',
    name: 'Gas Cylinder / LPG Tank',
    nameFr: 'Bouteille de Gaz / Réservoir GPL',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'prohibited',
    description: 'Pressurized flammable gas. Absolutely prohibited for standard freight. Requires specialized hazardous materials carrier and UN-certified packaging. We do not handle these.',
    descriptionFr: 'Gaz inflammable sous pression. Absolument interdit pour le fret standard. Nécessite un transporteur spécialisé en matières dangereuses et un emballage certifié UN. Nous ne gérons pas cela.',
    icon: 'Cylinder',
    notes: 'Contact a certified hazmat forwarder. Empty cylinders must be certified gas-free.',
    notesFr: 'Contactez un transitaire certifié pour matières dangereuses. Les bouteilles vides doivent être certifiées sans gaz.',
  },
  {
    id: 'lighter',
    name: 'Lighters / Matches / Firestarter',
    nameFr: 'Briquets / Allumettes / Allume-feu',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'prohibited',
    description: 'Flammable solids and gases. Lighters with fuel are prohibited. Empty lighters may be allowed but are high risk. Matches in large quantities are restricted.',
    descriptionFr: 'Solides et gaz inflammables. Les briquets avec carburant sont interdits. Les briquets vides peuvent être autorisés mais sont à haut risque. Les allumettes en grandes quantités sont restreintes.',
    icon: 'Flame',
    notes: 'Completely empty lighters (no fuel residue) may be allowed with declaration.',
    notesFr: 'Les briquets complètement vides (pas de résidu de carburant) peuvent être autorisés avec déclaration.',
  },
  {
    id: 'battery-acid',
    name: 'Car Battery / Battery Acid',
    nameFr: 'Batterie Auto / Acide de Batterie',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'prohibited',
    description: 'Lead-acid batteries contain corrosive sulfuric acid and are classified as dangerous goods. Wet cell batteries are prohibited. AGM and gel batteries may be shipped under strict rules.',
    descriptionFr: 'Les batteries au plomb contiennent de l\'acide sulfurique corrosif et sont classées comme marchandises dangereuses. Les batteries à électrolyte liquide sont interdites. Les batteries AGM et gel peuvent être expédiées sous des règles strictes.',
    icon: 'BatteryWarning',
    notes: 'Dry/sealed AGM batteries can sometimes ship via sea freight with MSDS. Contact us.',
    notesFr: 'Les batteries AGM sèches/scellées peuvent parfois être expédiées par fret maritime avec MSDS. Contactez-nous.',
  },
  {
    id: 'pesticide',
    name: 'Pesticide / Herbicide / Insecticide',
    nameFr: 'Pesticide / Herbicide / Insecticide',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'prohibited',
    description: 'Toxic chemicals. Most African countries strictly regulate or prohibit pesticide imports without agricultural ministry approval. We do not ship pesticides.',
    descriptionFr: 'Produits chimiques toxiques. La plupart des pays africains réglementent strictement ou interdisent les importations de pesticides sans approbation du ministère de l\'agriculture. Nous n\'expédions pas de pesticides.',
    icon: 'Bug',
    notes: 'Specialized agricultural importers with proper licenses can handle these. We can refer you.',
    notesFr: 'Des importateurs agricoles spécialisés avec les licences appropriées peuvent gérer cela. Nous pouvons vous orienter.',
  },
  {
    id: 'cleaning-chemicals',
    name: 'Bleach / Strong Cleaning Chemicals',
    nameFr: 'Javel / Produits de Nettoyage Forts',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'restricted',
    description: 'Corrosive and oxidizing substances. Bleach (sodium hypochlorite) is particularly dangerous. Limited quantities. Must be in original sealed containers. Never mix with other chemicals.',
    descriptionFr: 'Substances corrosives et oxydantes. L\'eau de javel (hypochlorite de sodium) est particulièrement dangereuse. Quantités limitées. Doit être dans des contenants scellés d\'origine. Ne jamais mélanger avec d\'autres produits chimiques.',
    icon: 'Trash2',
    notes: 'Max 5L per shipment. Must be upright and individually sealed in plastic bags.',
    notesFr: 'Max 5L par envoi. Doit être à la verticale et scellé individuellement dans des sacs plastique.',
  },
  {
    id: 'magnet',
    name: 'Strong Magnets / Magnetic Materials',
    nameFr: 'Aimants Puissants / Matériaux Magnétiques',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'restricted',
    description: 'Strong magnets can interfere with aircraft navigation systems. Must be properly shielded and declared. Neodymium (rare earth) magnets are highest risk. Small fridge magnets are fine.',
    descriptionFr: 'Les aimants puissants peuvent interférer avec les systèmes de navigation des avions. Doivent être correctement blindés et déclarés. Les aimants néodyme (terres rares) sont les plus à risque. Les petits aimants pour frigo sont acceptés.',
    icon: 'Magnet',
    notes: 'Magnetic field strength must be below 0.00525 gauss at 4.6m for air freight.',
    notesFr: 'L\'intensité du champ magnétique doit être inférieure à 0,00525 gauss à 4,6m pour le fret aérien.',
  },
  {
    id: 'aerosol-paint',
    name: 'Spray Paint / Aerosol Products',
    nameFr: 'Peinture en Spray / Produits Aérosol',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'restricted',
    description: 'Flammable pressurized aerosol. Same rules as cosmetic aerosols but often higher volume. Sea freight recommended for quantities over 5 cans.',
    descriptionFr: 'Aérosol inflammable sous pression. Mêmes règles que les aérosols cosmétiques mais souvent en plus grand volume. Fret maritime recommandé pour les quantités supérieures à 5 bombes.',
    icon: 'SprayCan',
  },
  {
    id: 'fireworks',
    name: 'Fireworks / Explosives / Ammunition',
    nameFr: 'Feux d\'Artifice / Explosifs / Munitions',
    category: 'dangerous',
    categoryFr: 'Matériaux Dangereux',
    status: 'prohibited',
    description: 'Class 1 explosives. Absolutely prohibited for civilian freight. Criminal penalties may apply. Includes fireworks, flares, blasting caps, and ammunition.',
    descriptionFr: 'Explosifs de classe 1. Absolument interdits pour le fret civil. Des sanctions pénales peuvent s\'appliquer. Inclut les feux d\'artifice, fusées éclairantes, détonateurs et munitions.',
    icon: 'Bomb',
  },

  // WEAPONS & SECURITY (8 items)
  {
    id: 'knife',
    name: 'Knives / Machetes / Cutting Tools',
    nameFr: 'Couteaux / Machettes / Outils de Coupe',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'restricted',
    description: 'Kitchen knives and tools are generally allowed if properly packaged. Switchblades, butterfly knives, and combat knives are prohibited. Machetes for agriculture may be allowed with justification.',
    descriptionFr: 'Les couteaux de cuisine et outils sont généralement autorisés si correctement emballés. Les couteaux à cran d\'arrêt, papillons et de combat sont interdits. Les machettes agricoles peuvent être autorisées avec justification.',
    icon: 'Sword',
    notes: 'Must be sheathed and wrapped. Declare as "kitchen/agricultural tool" on invoice.',
    notesFr: 'Doit être gainé et enveloppé. Déclarer comme "outil de cuisine/agricole" sur la facture.',
  },
  {
    id: 'toy-gun',
    name: 'Toy Guns / Replica Weapons / BB Guns',
    nameFr: 'Fusils Jouets / Répliques d\'Armes / Airsoft',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'prohibited',
    description: 'Replica weapons are prohibited in most African countries. Customs cannot distinguish replicas from real weapons. Airsoft guns with plastic pellets are also prohibited.',
    descriptionFr: 'Les répliques d\'armes sont interdites dans la plupart des pays africains. Les douanes ne peuvent pas distinguer les répliques des vraies armes. Les pistolets airsoft avec billes plastique sont également interdits.',
    icon: 'Crosshair',
  },
  {
    id: 'pepper-spray',
    name: 'Pepper Spray / Tear Gas / Stun Gun',
    nameFr: 'Bombe Lacrymogène / Gaz CS / Taser',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'prohibited',
    description: 'Self-defense weapons classified as dangerous goods and/or weapons. Prohibited for import in most African countries without police/army authorization.',
    descriptionFr: 'Armes d\'autodéfense classées comme marchandises dangereuses et/ou armes. Interdites à l\'importation dans la plupart des pays d\'Afrique sans autorisation police/armée.',
    icon: 'ShieldAlert',
  },
  {
    id: 'bulletproof-vest',
    name: 'Bulletproof Vest / Tactical Gear',
    nameFr: 'Gilet Pare-Balles / Équipement Tactique',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'permit-required',
    description: 'Military-grade equipment requires Ministry of Defense import permit in most countries. Civilian tactical gear (without armor plates) may be allowed with police declaration.',
    descriptionFr: 'L\'équipement militaire nécessite un permis d\'importation du Ministère de la Défense dans la plupart des pays. L\'équipement tactique civil (sans plaques pare-balles) peut être autorisé avec déclaration policière.',
    icon: 'Shield',
  },
  {
    id: 'handcuffs',
    name: 'Handcuffs / Police Equipment',
    nameFr: 'Menottes / Équipement de Police',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'permit-required',
    description: 'Law enforcement equipment requires special authorization. Private security companies may import with proper licensing from Ministry of Interior.',
    descriptionFr: 'L\'équipement des forces de l\'ordre nécessite une autorisation spéciale. Les sociétés de sécurité privée peuvent importer avec les licences appropriées du Ministère de l\'Intérieur.',
    icon: 'Lock',
  },
  {
    id: 'slingshot',
    name: 'Slingshot / Bow / Crossbow',
    nameFr: 'Lance-Pierre / Arc / Arbalète',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'restricted',
    description: 'Sporting bows and slingshots may be allowed with declaration. Crossbows are often classified as weapons and restricted. Hunting equipment may need wildlife ministry permit.',
    descriptionFr: 'Les arcs sportifs et lance-pierres peuvent être autorisés avec déclaration. Les arbalètes sont souvent classées comme armes et restreintes. L\'équipement de chasse peut nécessiter un permis du ministère de la faune.',
    icon: 'Target',
  },
  {
    id: 'body-armor',
    name: 'Body Armor / Helmet / Protective Gear',
    nameFr: 'Armure / Casque / Équipement de Protection',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'allowed',
    description: 'Motorcycle helmets, construction hard hats, and sports protective gear are allowed. NIJ-rated ballistic armor may require permit depending on protection level.',
    descriptionFr: 'Casques de moto, casques de chantier et équipement de protection sportif sont autorisés. L\'armure balistique certifiée NIJ peut nécessiter un permis selon le niveau de protection.',
    icon: 'HardHat',
  },
  {
    id: 'night-vision',
    name: 'Night Vision / Thermal Imaging',
    nameFr: 'Vision Nocturne / Imagerie Thermique',
    category: 'weapons',
    categoryFr: 'Armes & Sécurité',
    status: 'permit-required',
    description: 'Military-grade night vision is controlled technology. Civilian hunting scopes are generally allowed. Thermal imaging cameras for agriculture/veterinary use may need permits.',
    descriptionFr: 'La vision nocturne militaire est une technologie contrôlée. Les lunettes de chasse civiles sont généralement autorisées. Les caméras thermiques pour usage agricole/vétérinaire peuvent nécessiter des permis.',
    icon: 'Eye',
  },

  // DOCUMENTS & MONEY (6 items)
  {
    id: 'cash',
    name: 'Cash / Currency / Money',
    nameFr: 'Espèces / Monnaie / Argent',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'prohibited',
    description: 'Physical cash is prohibited in all standard freight. Use bank transfers (we offer supplier payment services) or Western Union/MoneyGram. Shipping cash will be seized.',
    descriptionFr: 'Les espèces physiques sont interdites dans tout fret standard. Utiliser les virements bancaires (nous offrons des services de paiement fournisseur) ou Western Union/MoneyGram. L\'expédition d\'espèces sera saisie.',
    icon: 'Banknote',
    notes: 'Use our safe supplier payment service instead. We pay your Chinese suppliers for you.',
    notesFr: 'Utilisez plutôt notre service de paiement fournisseur sécurisé. Nous payons vos fournisseurs chinois pour vous.',
  },
  {
    id: 'passport',
    name: 'Passport / ID Documents / Certificates',
    nameFr: 'Passeport / Pièces d\'Identité / Certificats',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'allowed',
    description: 'Important documents can be shipped via courier in document envelopes. We recommend using tracked document shipping. Make copies before shipping originals.',
    descriptionFr: 'Les documents importants peuvent être expédiés par coursier dans des enveloppes pour documents. Nous recommandons d\'utiliser un envoi de documents suivi. Faire des copies avant d\'expédier les originaux.',
    icon: 'FileText',
    notes: 'Use waterproof envelope. Keep tracking number. Consider DHL for urgent passports.',
    notesFr: 'Utiliser une enveloppe imperméable. Conserver le numéro de suivi. Envisager DHL pour les passeports urgents.',
  },
  {
    id: 'check',
    name: 'Checks / Bank Drafts / Securities',
    nameFr: 'Chèques / Traites Bancaires / Valeurs Mobilières',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'allowed',
    description: 'Negotiable instruments can be shipped as documents. Use registered/tracked shipping. Declare as "business documents" on invoice with zero declared value.',
    descriptionFr: 'Les instruments négociables peuvent être expédiés comme documents. Utiliser un envoi recommandé/suivi. Déclarer comme "documents commerciaux" sur la facture avec une valeur déclarée de zéro.',
    icon: 'Receipt',
  },
  {
    id: 'diploma',
    name: 'Diplomas / Degrees / Academic Records',
    nameFr: 'Diplômes / Certificats / Relevés de Notes',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'allowed',
    description: 'Academic documents can be shipped as standard documents. We recommend waterproof packaging and tracking. Apostille/legalization documents follow same rules.',
    descriptionFr: 'Les documents académiques peuvent être expédiés comme documents standard. Nous recommandons un emballage imperméable et le suivi. Les documents d\'apostille/légalisation suivent les mêmes règles.',
    icon: 'GraduationCap',
  },
  {
    id: 'gift-card',
    name: 'Gift Cards / Prepaid Cards / SIM Cards',
    nameFr: 'Cartes Cadeaux / Cartes Prépayées / Cartes SIM',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'allowed',
    description: 'Plastic cards are allowed. Bulk SIM cards may raise customs questions about resale. Gift cards with value should be declared. Keep PIN codes separate from physical cards.',
    descriptionFr: 'Les cartes plastiques sont autorisées. Les cartes SIM en vrac peuvent soulever des questions douanières concernant la revente. Les cartes cadeaux avec valeur doivent être déclarées. Garder les codes PIN séparés des cartes physiques.',
    icon: 'CreditCard',
  },
  {
    id: 'counterfeit-money',
    name: 'Counterfeit Currency / Fake Documents',
    nameFr: 'Fausse Monnaie / Faux Documents',
    category: 'documents',
    categoryFr: 'Documents & Argent',
    status: 'prohibited',
    description: 'Obviously illegal. Will be seized and reported to police. Includes prop money, fake IDs, forged certificates, and counterfeit goods.',
    descriptionFr: 'Évidemment illégal. Sera saisi et signalé à la police. Inclut l\'argent de décor, fausses pièces d\'identité, certificats falsifiés et produits de contrefaçon.',
    icon: 'AlertOctagon',
  },

  // AGRICULTURE (8 items)
  {
    id: 'seeds',
    name: 'Seeds / Planting Material',
    nameFr: 'Graines / Matériel de Plantation',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'permit-required',
    description: 'Requires phytosanitary certificate and agriculture ministry import permit. Must be certified disease-free. Genetically modified seeds have additional restrictions. Many countries protect local seed markets.',
    descriptionFr: 'Nécessite un certificat phytosanitaire et un permis d\'importation du ministère de l\'agriculture. Doit être certifié sans maladie. Les semences génétiquement modifiées ont des restrictions supplémentaires. De nombreux pays protègent les marchés locaux des semences.',
    icon: 'Sprout',
    notes: 'We do not ship seeds. Contact specialized agricultural suppliers with proper permits.',
    notesFr: 'Nous n\'expédions pas de graines. Contactez des fournisseurs agricoles spécialisés avec les permis appropriés.',
  },
  {
    id: 'fertilizer',
    name: 'Fertilizer / Manure / Soil',
    nameFr: 'Engrais / Fumier / Terreau',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'permit-required',
    description: 'Ammonium nitrate fertilizers are often explosive precursors and heavily regulated. Organic fertilizers need sanitary certificates. Soil is prohibited due to biosecurity risk.',
    descriptionFr: 'Les engrais au nitrate d\'ammonium sont souvent des précurseurs explosifs et fortement réglementés. Les engrais organiques nécessitent des certificats sanitaires. Le terreau est interdit en raison du risque de biosécurité.',
    icon: 'Leaf',
    notes: 'We do not handle fertilizers. Contact specialized agricultural logistics providers.',
    notesFr: 'Nous ne gérons pas les engrais. Contactez des prestataires logistiques agricoles spécialisés.',
  },
  {
    id: 'pest-trap',
    name: 'Pest Trap / Agricultural Tools',
    nameFr: 'Piège à Nuisibles / Outils Agricoles',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'allowed',
    description: 'Standard agricultural tools, sprayers (non-motorized), nets, and traps are allowed. Motorized sprayers follow machinery rules. Ensure no pesticide residue on used equipment.',
    descriptionFr: 'Les outils agricoles standard, pulvérisateurs (non motorisés), filets et pièges sont autorisés. Les pulvérisateurs motorisés suivent les règles des machines. S\'assurer qu\'il n\'y a pas de résidus de pesticides sur l\'équipement usagé.',
    icon: 'Shovel',
  },
  {
    id: 'live-plant',
    name: 'Live Plants / Trees / Cuttings',
    nameFr: 'Plantes Vivantes / Arbres / Boutures',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'prohibited',
    description: 'Live plants are prohibited for standard freight due to biosecurity risk, CITES restrictions, and phytosanitary requirements. Specialized plant importers with quarantine facilities can handle these.',
    descriptionFr: 'Les plantes vivantes sont interdites pour le fret standard en raison du risque de biosécurité, des restrictions CITES et des exigences phytosanitaires. Des importateurs de plantes spécialisés avec installations de quarantaine peuvent gérer cela.',
    icon: 'TreePine',
  },
  {
    id: 'animal-feed',
    name: 'Animal Feed / Pet Food',
    nameFr: 'Aliment Animale / Nourriture pour Animaux',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'allowed',
    description: 'Commercially packaged pet food and animal feed is allowed. Must have ingredient list and expiry date. Raw/uncooked feed may have additional restrictions.',
    descriptionFr: 'La nourriture pour animaux emballée commercialement et les aliments pour bétail sont autorisés. Doit avoir la liste des ingrédients et la date de péremption. Les aliments crus/non cuits peuvent avoir des restrictions supplémentaires.',
    icon: 'Bone',
  },
  {
    id: 'fishing-gear',
    name: 'Fishing Net / Rod / Aquaculture Equipment',
    nameFr: 'Filet de Pêche / Canne / Équipement Aquaculture',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'allowed',
    description: 'Fishing equipment is allowed. Large nets should be compactly bundled. Electric fishing devices are prohibited. Fish finders with lithium batteries follow electronics rules.',
    descriptionFr: 'L\'équipement de pêche est autorisé. Les grands filets doivent être compactement ficelés. Les dispositifs de pêche électrique sont interdits. Les sondeurs de poissons avec batteries lithium suivent les règles de l\'électronique.',
    icon: 'Fish',
  },
  {
    id: 'beekeeping',
    name: 'Beekeeping Equipment / Hives',
    nameFr: 'Équipement Apicole / Ruches',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'allowed',
    description: 'Empty beehives and beekeeping suits are allowed. Live bees are prohibited. Used hives with wax residue may require sanitary treatment certificate.',
    descriptionFr: 'Les ruches vides et les combinaisons d\'apiculture sont autorisées. Les abeilles vivantes sont interdites. Les ruches usagées avec résidus de cire peuvent nécessiter un certificat de traitement sanitaire.',
    icon: 'Hexagon',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse / Irrigation Equipment',
    nameFr: 'Serre / Équipement d\'Irrigation',
    category: 'agriculture',
    categoryFr: 'Agriculture',
    status: 'allowed',
    description: 'Greenhouse frames, plastic sheeting, drip irrigation tubing, and sprinklers are allowed. Solar pumps follow solar panel rules. Large shipments best by sea freight.',
    descriptionFr: 'Les structures de serre, bâches plastiques, tuyaux d\'irrigation goutte-à-goutte et arroseurs sont autorisés. Les pompes solaires suivent les règles des panneaux solaires. Les grandes quantités sont meilleures par fret maritime.',
    icon: 'CloudRain',
  },
];

export const POPULAR_SEARCHES = [
  'phone',
  'battery',
  'perfume',
  'medicine',
  'shoes',
  'generator',
  'cosmetics',
  'food',
];

export const SHIPPING_ADVICE: Record<string, { en: string; fr: string }> = {
  electronics: {
    en: 'Keep original packaging. Declare battery capacity. Remove SIM cards.',
    fr: 'Conserver l\'emballage d\'origine. Déclarer la capacité de la batterie. Retirer les cartes SIM.',
  },
  cosmetics: {
    en: 'Seal caps with tape. Pack upright. Declare flammable contents.',
    fr: 'Sceller les bouchons avec du ruban adhésif. Emballer à la verticale. Déclarer les contenus inflammables.',
  },
  food: {
    en: 'Check expiry dates. Ensure commercial packaging. Verify destination country food rules.',
    fr: 'Vérifier les dates de péremption. S\'assurer d\'un emballage commercial. Vérifier les règles alimentaires du pays de destination.',
  },
  textiles: {
    en: 'No special requirements. Bulk sea freight recommended for large quantities.',
    fr: 'Aucune exigence spéciale. Fret maritime en vrac recommandé pour les grandes quantités.',
  },
  machinery: {
    en: 'Drain all fluids. Disconnect battery. Use wooden crating for heavy items.',
    fr: 'Vider tous les liquides. Débrancher la batterie. Utiliser un caissage en bois pour les articles lourds.',
  },
  medical: {
    en: 'Keep original packaging. Include instructions. Check expiry dates.',
    fr: 'Conserver l\'emballage d\'origine. Inclure les notices. Vérifier les dates de péremption.',
  },
  dangerous: {
    en: 'DO NOT SHIP without consulting us first. Special handling required.',
    fr: 'NE PAS EXPÉDIER sans nous consulter d\'abord. Manipulation spéciale requise.',
  },
  weapons: {
    en: 'Most items in this category are prohibited or require special permits. Contact us.',
    fr: 'La plupart des articles de cette catégorie sont interdits ou nécessitent des permis spéciaux. Contactez-nous.',
  },
  documents: {
    en: 'Use waterproof envelope. Keep tracking number. Consider courier for urgent items.',
    fr: 'Utiliser une enveloppe imperméable. Conserver le numéro de suivi. Envisager un coursier pour les articles urgents.',
  },
  agriculture: {
    en: 'Seeds and fertilizers require permits. We do not handle live plants or pesticides.',
    fr: 'Les graines et engrais nécessitent des permis. Nous ne gérons pas les plantes vivantes ou pesticides.',
  },
};
